services:
  payment-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudgame-payment-api
    depends_on:
      rabbitmq:
        condition: service_healthy
      sqlserver:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__CloudGameDb: Server=sqlserver,1433;Database=PaymentDb;User Id=phSvicero;Password=paymentCG;TrustServerCertificate=True
      RabbitMq__Host: rabbitmq
      RabbitMq__VirtualHost: /
      RabbitMq__Username: guest
      RabbitMq__Password: guest
      RabbitMq__OrderPlacedQueue: payments.order-placed
      PaymentProcessing__ApprovalPercentage: 80
      PaymentProcessing__DefaultPaymentType: CreditCard
    ports:
      - "5059:8080"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cloudgame-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cloudgame-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Your_password123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
