services:
  cloudgamepaymentapi:
    image: ${DOCKER_REGISTRY-}cloudgamepaymentapi
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - '8082:8080'
      - '8083:8081'
    restart: unless-stopped    
    networks:
      - cloudgame-network
  
networks:
  cloudgame-network:
    external: true
    name: cloudgame-network