apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-api-config
data:
  ASPNETCORE_URLS: http://+:8080
  ASPNETCORE_ENVIRONMENT: Production
  RabbitMq__Host: rabbitmq
  RabbitMq__VirtualHost: /
  RabbitMq__OrderPlacedQueue: payments.order-placed
  PaymentProcessing__ApprovalPercentage: "80"
  PaymentProcessing__DefaultPaymentType: CreditCard
